# Generated by Django 5.1.5 on 2025-03-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
